### ISSUE TITLE
Follow Java habit about overload

### ISSUE THREAD

**Issue by LeonLiuY** [wapatesh/fig#5]
We have many methods named 

`forEach`, `forEachWithIndex`.

Maybe we can use the same name but overload methods instead, it follows the custom of Java.

And maybe easier for users to remember all the names.

**Comment by WangBoxue** [comment]
The compiler will produce errors `Ambiguous method call` when the parameter is null if these two functions have the same name.

**Comment by LeonLiuY** [comment]
Isn't it better that compiler reject null as parameter?

Since null is of course illegal.

**Comment by WangBoxue** [comment]
Yes, this can free us from null detection. 
But I don't think errors produced by compiler is very convenient to users. 
Because usually, errors produced by compiler are about wrong usage, wrong parameters, syntax errors. 
I mean illegal parameters should be handled by ourselves, not by the compiler.

**Comment by LeonLiuY** [comment]
Yes, we should not rely on compiler. And actually we can not, if you give the null a type, compiler will pass:

```
Type a = null
method(a);
```

What I want to say is `Ambiguous method call` seems not a good reason to stop us using overload on methods.
